# Font configuration : jetbrain mono
[font]
size = 12

[font.normal]
family = "JetBrains Mono"
style = "SemiBold"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Heavy Italic"

[font.italic]
family = "JetBrains Mono"
style = "Medium Italic"

[font.offset]
x = 0
y = 1
