# Font configuration : jetbrain mono
[font]
size = 12

# [font.normal]
# family = "JetBrains Mono"
# style = "SemiBold"

# [font.bold]
# family = "JetBrains Mono"
# style = "Bold"

# [font.bold_italic]
# family = "JetBrains Mono"
# style = "Heavy Italic"

# [font.italic]
# family = "JetBrains Mono"
# style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.offset]
x = 0
y = 1
