# Font configuration : jetbrain mono
[font]
size = 12.0

# [normal]
normal.family = "JetBrains Mono"
normal.style = "Regular"

# [bold]
bold.family = "JetBrains Mono"
bold.style = "Heavy"

# [bold_italic]
bold_italic.family = "JetBrains Mono"
bold_italic.style = "Heavy Italic"

# [italic]
italic.family = "JetBrains Mono"
italic.style = "Medium Italic"

# [offset]
offset.x = 0
offset.y = 1
