[keyboard]
bindings = [
	# Alt + J/K : drag lines in lunarvim (default keybinds)
	{ key = "J", mods = "Alt", chars = "\u001bj" },
	{ key = "K", mods = "Alt", chars = "\u001bk" },

	# macOS Option defaults to character composition; emit Alt + M for MultiView
	{ key = "M", mods = "Alt", chars = "\u001bm" },

	# sends a newline to the CLI instead of executing the command
	{ key = "Return", mods = "Shift", chars = "\u001B\r" },

	# rebinds cmd + capslock + w to recevice a 'w' instead of
	# closing the window, which is the default behavior on macOS
	{ key = "W", mods = "Command", action = "ReceiveChar" },
]
