#!/usr/bin/env zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

# custom env vars
export RELEASES="$HOME/Releases"

# XDG Directoriess
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"


# zsh stuff
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/zsh_history"


# Globals vars
if command -v lvim &> /dev/null; then
	export EDITOR="$HOME/.local/bin/lvim"
fi


# golang
export GOPATH="$RELEASES/go"
export GOBIN="$RELEASES/go/bin"
export GOCACHE="$XDG_CACHE_HOME/go-build"


# NPM
export NPM_PATH="$XDG_CONFIG_HOME/node_modules"
export NPM_BIN="$NPM_PATH/bin"


# zellij
export ZELLIJ_CONFIG_DIR="$XDG_CONFIG_HOME/zellij"
. "$HOME/.cargo/env"
